---
title: "LinearRegression_MarketingAnalytics"
author: "Sanmoy Paul"
date: "15 April 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Load Libraries**
```{r LoadLibraries, echo=TRUE}  
library(dplyr)
library(tidyr)
library(MASS)
library(caTools)
library(ISLR)
library(car)
library(ggplot2)
library(plotly)
library(gridExtra)
``` 

**Read Data**
```{r readData, echo=TRUE}
presData<-as.data.frame(Prestige)
```   

**Read First 6 recs**
```{r ReadFirst, echo=TRUE}
head(presData)
```
**Read Last 6 recs**
```{r ReadLast, echo=TRUE}
tail(presData)
```

**Structure of the data frame**
```{r struc, echo=TRUE}
str(presData)
glimpse(presData)
```

**No of Cols**
```{r nCol, echo=TRUE}
ncol(presData)
```

**No of rows**
```{r nRow, echo=TRUE}
nrow(presData)
```

**Names**
```{r colNames, echo=TRUE}
names(presData)
colnames(presData)
```  

**Detect NAs**
```{r detectNAs, echo=TRUE}
detectNAs<-function(x){
  return(sum(is.na(x)))
}
lapply(presData, detectNAs)
```  

**Remove NAs**
```{r omitNAs, echo=TRUE}
presData<-na.omit(presData)
```  

**Summary stat**
```{r summaryStat, echo=TRUE}
summary(presData)
```  

**Plots**
```{r plots, echo=TRUE}
p1<-ggplot(presData, aes(x=education)) + geom_histogram( binwidth = 1)+
  labs(title="Histogram of Average years of Education") +
  labs(x="average years of Education") +
  labs(y="Frequency Count")

p2<-ggplot(presData, aes(x=income)) + geom_histogram( binwidth = 1000)+
  labs(title="Histogram of Income") +
  labs(x="Income") +
  labs(y="Frequency Count")

p3<-ggplot(presData, aes(x=education, y=income)) + geom_point( position="jitter")+
  labs(title="Relationship between Education and Income") +
  labs(x="Education") +
  labs(y="Income")

p4<-ggplot(presData, aes(x=education, y=income)) + geom_point() + geom_smooth( method="lm", se=FALSE)+
  labs(title="Linear Relationship between Education and Income") +
  labs(x="Education") +
  labs(y="Income")
grid.arrange(p1,p2, p3, p4, nrow=2, ncol=2)
```

**Split Data into Traind and Test Sets**
```{r splittingData, echo=TRUE}
set.seed(100)
split<-sample.split(presData$income, SplitRatio=0.8)
trainSet<-subset(presData, split==TRUE)
testSet<-subset(presData, split==FALSE)  
```

**Model1**
```{r model1, echo=TRUE}
lm.fit1<-lm(income~., data=trainSet)
lm.fit1
summary(lm.fit1)
```

**Model2**
```{r model2, echo=TRUE}
lm.fit2<-lm(income~education, data=trainSet)
lm.fit2
summary(lm.fit2)
```

**Model3**
```{r model3, echo=TRUE}
lm.fit3<-lm(income~(prestige+women), data=trainSet)
lm.fit3
summary(lm.fit3)
```

**Prediction_1**
```{r prediction1, echo=TRUE}
predict1<-predict(lm.fit2, newdata = testSet)
predict1_df<-as.data.frame(predict1)
```

**Prediction_2**
```{r prediction2, echo=TRUE}
predict2<-predict(lm.fit3, newdata = testSet)
predict2_df<-as.data.frame(predict2)
```

**Predicted Results**
```{r predictedResults, echo=TRUE}
names<-row.names(testSet)
lm._df<-data.frame(ActualIncome=testSet$income, 
                  PredictedIncome_1=predict1_df$predict1, PredictedIncome_2=predict2_df$predict2)

lm._df
```
